# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Maxime Fosset"                                # Your name
  description: "Intensive care medicine and causal inference practictioner"   # A brief slogan (optional)
  image: img/profile_picture_small.jpg
  
  #favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    #logo: /img/PreMeDICal_Logo.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: blog/404.qmd
    #  - text: "Talks"
    #    href: talks/index.qmd
        #Publications Resources Talks Blog CV Medicine R tips
    
    # your social media handles
    right:
      - icon: twitter
        href: https://x.com/MaximeFosset
      - icon: github
        href: https://github.com/MFosset
      - icon: envelope
        aria-label: email
        href: "mailto:max.fosset@gmail.com"  
      - icon: google scholar
        href: "https://scholar.google.com/citations?user=Eh8RiMIAAAAJ&hl=en"
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Maxime Fosset CC BY-SA 4.0</span>
    #center: |
    #  <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template</a></span>
    #right: |
    #  <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true